"use client";
import Link from "@/components/page-link";
import {useEffect,useState} from "react";
import {CalendarDays,MessageCircle,UserRound,ArrowUpRight,LogOut} from "lucide-react";
import {SitePage} from "@/components/site-shell";
import {serviceName,type Lang} from "@/lib/catalog";
import {statusLabel,errorText} from "@/lib/client";
type Profile={user:{id:string;name:string;email:string}|null;bookings:{id:string;vehicle:string;service:string;date:string;time:string;status:string}[];history:{role:string;text:string}[]};
async function accountAction(action:string,data:Record<string,unknown>={}) {
  const r=await fetch("/api/account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...data})});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||"UNAVAILABLE");return b;
}
function Account({lang}:{lang:Lang}) {
  const t=(z:string,e:string)=>lang==="zh"?z:e;
  const [profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [signup,setSignup]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState("");
  async function load(){try{const r=await fetch("/api/account");const b=await r.json() as Profile & {error?:string};if(!r.ok)throw new Error(b.error||"UNAVAILABLE");setProfile(b);setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{
    let active=true;
    fetch("/api/account").then(async r=>{const b=await r.json() as Profile & {error?:string};if(!r.ok)throw new Error(b.error||"UNAVAILABLE");return b}).then(b=>{if(active)setProfile(b)}).catch(e=>{if(active)setError((e as Error).message)}).finally(()=>{if(active)setLoading(false)});
    return()=>{active=false};
  },[]);
  async function submit(){setBusy(true);setError("");try{await accountAction(signup?"signup":"login",{name,email,password});setPassword("");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function action(value:string){setBusy(true);setError("");try{await accountAction(value);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="page-container account-page"><div className="page-heading"><p className="eyebrow">{t("我的 HARBOUR","MY HARBOUR")}</p><h1>{profile?.user?t("你好，","Hello, ")+profile.user.name:t("你的车辆。你的账户。","Your car. Your account.")}</h1><p>{t("在同一个地方管理预约，继续之前的车辆咨询。","Manage your visits and pick up your car care conversations in one place.")}</p></div>
    {loading&&<p role="status" className="page-footnote">{t("正在读取账户…","Loading your account…")}</p>}
    {error&&<p className="error" role="alert">{errorText(error,lang)}{!profile&&<button className="link" onClick={load}>{t("重试","Retry")}</button>}</p>}
    {!loading&&profile&&!profile.user&&<div className="account-entry"><section className="account-benefits"><UserRound size={36}/><h2>{t("少一点重复，多一点从容。","Less repetition. More peace of mind.")}</h2><p>{t("登录后新建的预约会出现在账户中，方便查看、改期和取消。聊天助手会保存最近的咨询记录。","Bookings created while signed in appear here for viewing, rescheduling and cancellation. The assistant saves your recent conversations.")}</p><Link className="link" href="/manage">{t("已有私人预约链接？","Already have a private booking link?")} <ArrowUpRight size={15}/></Link></section><form className="dark-panel account-form" onSubmit={e=>{e.preventDefault();void submit()}}><div className="account-tabs"><button type="button" aria-pressed={!signup} onClick={()=>{setSignup(false);setError("")}}>{t("登录","Sign in")}</button><button type="button" aria-pressed={signup} onClick={()=>{setSignup(true);setError("")}}>{t("创建账户","Create account")}</button></div><h2>{signup?t("欢迎加入 Harbour","Welcome to Harbour"):t("欢迎回来","Welcome back")}</h2>{signup&&<label className="field">{t("显示姓名","Display name")}<input required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}<label className="field">{t("邮箱","Email")}<input required type="email" maxLength={150} autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">{t("密码","Password")}<input required type="password" minLength={12} maxLength={128} autoComplete={signup?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="small muted">{t("至少 12 个字符。暂未启用自助密码找回，请保存好密码。","At least 12 characters. Self-service password recovery is not enabled; keep your password safe.")}</p><button className="primary full" disabled={busy}>{busy?t("正在处理…","Working…"):signup?t("创建账户","Create account"):t("登录","Sign in")}</button><p className="small muted">{t("继续即表示你已阅读","By continuing, you acknowledge the ")} <Link href="/terms">{t("条款与隐私说明","terms & privacy notice")}</Link>{lang==="zh"?"。":"."}</p></form></div>}
    {profile?.user&&<><div className="account-toolbar"><span>{profile.user.email}</span><button className="secondary" disabled={busy} onClick={()=>action("logout")}><LogOut size={16}/>{t("退出登录","Sign out")}</button></div><section className="account-section"><div className="account-section-title"><h2><CalendarDays/>{t("我的预约","My visits")}</h2><Link className="primary" href="/#booking">{t("新建预约","Book a visit")}</Link></div>{profile.bookings.length?<div className="visits-grid">{profile.bookings.map(row=><article key={row.id} className="dark-panel"><div className="visit-top"><span className="status">{statusLabel(row.status,lang)}</span><span>{row.id.slice(0,8).toUpperCase()}</span></div><h3>{serviceName(row.service,lang)}</h3><p>{row.vehicle}</p><p className="visit-time">{row.date} · {row.time}</p><Link className="secondary" href={`/manage?id=${row.id}`}>{t("查看和管理","View & manage")}<ArrowUpRight size={16}/></Link></article>)}</div>:<div className="account-empty">{t("暂无账户预约。请在登录状态下提交新的预约；旧的访客预约仍使用私人链接管理。","No account bookings yet. Create your next booking while signed in; existing guest bookings still use their private links.")}</div>}</section><section className="account-section"><div className="account-section-title"><h2><MessageCircle/>{t("最近的咨询","Recent conversations")}</h2>{profile.history.length>0&&<button className="secondary" disabled={busy} onClick={()=>action("clearHistory")}>{t("清除记录","Clear history")}</button>}</div><p className="page-footnote">{t("点击右下角咨询按钮继续对话。最多保留最近 60 条消息，仅对你的账户开放。","Use the assistant button to continue chatting. The latest 60 messages are saved privately to your account.")}</p>{profile.history.length?<div className="account-history">{profile.history.map((m,i)=><article className={"saved-message "+m.role} key={i}><strong>{m.role==="user"?t("你","You"):"Harbour"}</strong><p>{m.text}</p></article>)}</div>:<div className="account-empty">{t("尚无保存的咨询。登录后与助手对话，记录会显示在这里。","No saved conversations yet. Chat with the assistant while signed in to see your history here.")}</div>}</section></>}
  </div>;
}
export default function AccountPage(){return <SitePage active="account">{lang=><Account lang={lang}/>}</SitePage>}
