"use client";
import {useState,useEffect,useRef} from "react";import {Check,CalendarDays,Copy} from "lucide-react";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {services,Lang,todaySydney,datePlus,serviceName} from "@/lib/catalog";import {api,errorText} from "@/lib/client";
export function ServiceSelect({value,onChange,lang}:{value:string,onChange:(v:string)=>void,lang:Lang}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="w-full h-11 text-base"><SelectValue/></SelectTrigger><SelectContent>{services.map(s=><SelectItem key={s.id} value={s.id}>{s[lang]}</SelectItem>)}</SelectContent></Select>}
export function SlotPicker({date,setDate,time,setTime,lang,refresh=0}:{date:string,setDate:(s:string)=>void,time:string,setTime:(s:string)=>void,lang:Lang,refresh?:number}){
 const [slots,setSlots]=useState<string[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const t=(z:string,e:string)=>lang==="zh"?z:e;
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");setSlots([]);fetch("/api/workshop?action=availability&date="+encodeURIComponent(date),{signal:controller.signal}).then(async r=>{const b:any=await r.json();if(!r.ok)throw new Error(b.error);setSlots(b.times)}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort();},[date,refresh]);
 return <><label className="field">{t("到店日期","Visit date")}<input type="date" value={date} min={todaySydney()} max={datePlus(todaySydney(),60)} onChange={e=>{setDate(e.target.value);setTime("")}} required/></label><p className="small muted">{t("可用到店时段 · 悉尼时间","Available check-in times · Sydney time")}</p>{loading?<p className="notice" role="status">{t("正在查询空闲时间…","Checking availability…")}</p>:error?<p className="error" role="alert">{errorText(error,lang)}</p>:slots.length?<div className="slots" aria-label={t("选择到店时间","Choose a time")}>{slots.map(s=><button type="button" aria-pressed={time===s} className={"slot "+(time===s?"active":"")} key={s} onClick={()=>setTime(s)}>{s}</button>)}</div>:<p className="notice">{t("当天已约满或不营业，请选择其他日期。","No available appointments on this day. Please choose another date.")}</p>}</>;
}
export default function Booking({lang,initialService="service",onDone}:{lang:Lang,initialService?:string,onDone?:()=>void}){
 const t=(z:string,e:string)=>lang==="zh"?z:e;const [service,setService]=useState(initialService),[date,setDate]=useState(datePlus(todaySydney(),1)),[time,setTime]=useState(""),[stage,setStage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<any>(null),[copied,setCopied]=useState(false),[refresh,setRefresh]=useState(0);
 const [form,setForm]=useState({name:"",email:"",phone:"",vehicle:"",notes:""});const identity=useRef<{requestId:string,token:string}|null>(null);
 useEffect(()=>{setService(initialService)},[initialService]);const s=services.find(x=>x.id===service)!;
 const update=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 async function submit(){setBusy(true);setError("");if(!identity.current)identity.current={requestId:crypto.randomUUID(),token:[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,"0")).join("")};try{const b=await api("create",{...form,service,date,time,...identity.current});setResult(b.booking);onDone?.();}catch(e){const code=(e as Error).message;setError(code);if(code==="SLOT_TAKEN"||code==="INVALID_SLOT"){setTime("");setStage(1);setRefresh(v=>v+1);}}finally{setBusy(false)}}
 if(result){const link=typeof window!=="undefined"?window.location.origin+"/manage?id="+result.id+"#"+identity.current!.token:"";return <div><div className="success-icon"><Check/></div><h2>{t("预约已保存","You're booked")}</h2><p className="notice">{serviceName(result.service,lang)} · {result.date} {result.time}<br/>{t("悉尼时间 · 到店接待时段","Sydney time · check-in appointment")}</p><p className="small muted">{t("预约编号","Booking reference")}</p><p style={{fontWeight:700,marginBottom:16}}>{result.id.slice(0,8).toUpperCase()}</p><p className="small">{t("请保存私人管理链接，用于查看、改期或取消。链接相当于预约凭证，请勿公开分享。目前不发送邮件或短信。","Save your private management link to view, reschedule or cancel. Keep it private; it grants access to this booking. Email and SMS are not sent.")}</p><input className="input" style={{margin:"14px 0",fontSize:".8rem"}} readOnly value={link} aria-label={t("私人管理链接","Private management link")}/><div className="actions"><a className="primary" href={link}>{t("管理此预约","Manage booking")}</a><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setCopied(false)}}}><Copy size={16}/>{copied?t("已复制","Copied"):t("复制链接","Copy link")}</button></div></div>}
 return <div><p className="step-title">{t("第 "+stage+" 步，共 3 步","Step "+stage+" of 3")} · {stage===1?t("选择服务和时间","Service & time"):stage===2?t("车辆和联系资料","Your details"):t("确认预约","Review booking")}</p>
 {stage===1&&<><label className="field">{t("服务项目","Service")}<ServiceSelect value={service} onChange={setService} lang={lang}/></label><SlotPicker date={date} setDate={setDate} time={time} setTime={setTime} lang={lang} refresh={refresh}/><p className="small muted" style={{marginBottom:18}}>{t("参考价","Demo estimate")}: A$ {s.min}–{s.max} · {t("到店检查后确认","confirmed after inspection")}</p><button className="primary full" disabled={!time} onClick={()=>{setError("");setStage(2)}}>{t("继续填写资料","Continue")}</button><button className="link" style={{marginTop:12}} onClick={()=>setRefresh(v=>v+1)}>{t("刷新可用时段","Refresh availability")}</button></>}
 {stage===2&&<form onSubmit={e=>{e.preventDefault();setError("");setStage(3)}}><label className="field">{t("姓名","Name")}<input required autoComplete="name" maxLength={80} value={form.name} onChange={e=>update("name",e.target.value)}/></label><label className="field">{t("邮箱","Email")}<input required type="email" autoComplete="email" maxLength={150} value={form.email} onChange={e=>update("email",e.target.value)}/></label><label className="field">{t("联系电话","Phone")}<input required type="tel" autoComplete="tel" minLength={6} maxLength={30} value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label className="field">{t("车辆品牌、车型和年份","Vehicle make, model & year")}<input required minLength={2} maxLength={120} placeholder="Toyota Corolla 2020" value={form.vehicle} onChange={e=>update("vehicle",e.target.value)}/></label><label className="field">{t("症状或备注（选填）","Symptoms or notes (optional)")}<textarea maxLength={1000} rows={2} value={form.notes} onChange={e=>update("notes",e.target.value)}/></label><p className="small muted" style={{marginBottom:16}}>{t("课堂演示请使用虚构联系资料。资料仅用于本次预约，店铺管理员可查看。","Use fictional contact details for this class demo. Details are used for the booking and are visible to the workshop administrator.")}</p><div className="row"><button type="button" className="secondary" onClick={()=>setStage(1)}>{t("返回","Back")}</button><button className="primary" type="submit">{t("查看确认信息","Review booking")}</button></div></form>}
 {stage===3&&<><dl className="detail-list"><dt>{t("服务","Service")}</dt><dd>{s[lang]}</dd><dt>{t("时间","Time")}</dt><dd>{date} · {time}<br/>{t("悉尼当地时间","Sydney local time")}</dd><dt>{t("车辆","Vehicle")}</dt><dd>{form.vehicle}</dd><dt>{t("姓名","Name")}</dt><dd>{form.name}</dd><dt>{t("联系方式","Contact")}</dt><dd>{form.email}<br/>{form.phone}</dd><dt>{t("参考费用","Estimate")}</dt><dd>A$ {s.min}–{s.max}</dd>{form.notes&&<><dt>{t("备注","Notes")}</dt><dd>{form.notes}</dd></>}</dl><p className="notice">{t("这是到店接待预约。维修内容、最终费用与取车时间需检查后确认。提交后请保存管理链接；不会发送确认邮件。","This reserves a check-in appointment. Repair scope, final cost and collection time follow inspection. Save the management link after submitting; no confirmation email is sent.")}</p><div className="row"><button disabled={busy} className="secondary" onClick={()=>setStage(2)}>{t("修改资料","Edit details")}</button><button disabled={busy} className="primary" onClick={submit}>{busy?t("正在保存…","Saving…"):t("确认并提交","Confirm booking")}</button></div></>}
 {error&&<p role="alert" className="error">{errorText(error,lang)}</p>}</div>;
}
