"use client";
import {SitePage} from "@/components/site-shell";
export default function TermsPage(){return <SitePage active="terms">{lang=>{const t=(z:string,e:string)=>lang==="zh"?z:e;const sections=[
 [t("预约与报价","Appointments & estimates"),t("提交成功并显示预约编号后，预约才算确认。预约为到店接待时段，不代表维修完成时间。价格为参考区间；具体项目、零件和人工需检查后确认。故障排查费用不含后续维修。网站未启用在线付款、邮件或短信通知。","A booking is confirmed only after a successful save and a booking reference appears. Your appointment reserves a check-in time, not a repair completion time. Prices are indicative; scope, parts and labour require inspection. Diagnosis excludes subsequent repairs. Online payments, email and SMS notifications are not enabled.")],
 [t("改期与取消","Changes & cancellations"),t("可通过私人管理链接，或登录创建此预约的账户，查看、改期和取消有效预约。请保管好私人链接；持有者可以管理对应预约。","Use your private management link, or the account that created the booking, to view, reschedule or cancel an active visit. Keep private links secure: anyone with the complete link can manage that booking.")],
 [t("账户与隐私","Accounts & privacy"),t("账户保存显示姓名、邮箱、加密后的密码验证值，以及登录期间新建的预约。原有访客预约不会仅凭邮箱自动关联。聊天记录仅对对应账户开放，最多保留最近 60 条消息，可在账户页面清除。密码、私人令牌和预约图片不会公开展示。当前未启用邮箱验证和自助密码找回，请保存好密码。","Accounts store your display name, email, a salted password hash and bookings created while signed in. Guest bookings are not automatically linked by email. Only your account can access its saved chat, limited to the latest 60 messages; you can clear it from your account page. Passwords, private tokens and booking images are not displayed publicly. Email verification and self-service password recovery are not currently enabled; keep your password safe.")],
 [t("图片与咨询","Photos & consultation"),t("预约最多可上传 2 张图片，每张不超过 20MB。图片仅供持有该预约访问权限的客户与店铺管理员查看。咨询文本可能发送至 OpenAI 以生成回复；请勿在聊天中输入敏感信息。聊天仅提供初步建议，不能确认诊断或行车安全。","A booking accepts up to two images, each no larger than 20MB. Photos are accessible only to the booking's authorised customer and workshop administrator. Consultation text may be sent to OpenAI to generate replies; keep sensitive information out of chat. Chat provides initial guidance and cannot confirm a diagnosis or that a vehicle is safe to drive.")],
 [t("公开留言","Public feedback"),t("留言区内容会公开显示，请勿发布联系方式、私人预约链接或敏感资料。店铺管理员可以隐藏不适当的留言。","Feedback is public. Do not post contact details, private booking links or sensitive information. The workshop administrator can hide inappropriate messages.")],
 ];return <div className="page-container policy-page"><div className="page-heading"><p className="eyebrow">HARBOUR AUTO</p><h1>{t("条款与隐私","Terms & privacy")}</h1><p>{t("了解预约、账户和网站数据的使用方式。","How appointments, accounts and website data work.")}</p></div>{sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</div>}}</SitePage>}
